Print error in knativeServingDelete (#268)
This makes a tiny change that knativeServingDelete prints missing error message.

Currently the error prints as:

```
    --- FAIL: TestKnativeServingDeployment/delete (30.65s)
        knativeservingdeployment_test.go:244: The CustomResourceDefinition ingresses.networking.internal.knative.dev failed to be deleted
```

and it is difficult to find the reason why `clients.Dynamic.Resource(gvrs).Get()` failed to delete.